parameters:

    #
    # Factories
    #
    elcodi.factory.metric_entry.class: Elcodi\Component\Metric\Core\Factory\EntryFactory

    #
    # Buckets
    #
    elcodi.redis_metrics_bucket.class: Elcodi\Component\Metric\Core\Bucket\RedisMetricsBucket

    #
    # Services
    #
    elcodi.metric_manager.class: Elcodi\Component\Metric\Core\Services\MetricManager

    #
    # Controllers
    #
    elcodi.controller.metric_input.class: Elcodi\Component\Metric\Input\Controller\InputController

    #
    # Routes
    #
    elcodi.core.metric.routes.input.loader.class: Elcodi\Component\Metric\Input\Router\MetricInputLoader

    #
    # Twig extensions
    #
    elcodi.api_metric_twig_extension.class: Elcodi\Component\Metric\API\Twig\APIMetricExtension
