services:

    #
    # Controllers
    #
    elcodi.controller.metric_input:
        class: %elcodi.controller.metric_input.class%
        arguments:
            - @request_stack
            - @elcodi.metric_manager
