services:

    #
    # Object Managers
    #
    elcodi.object_manager.entry:
        class: Doctrine\Common\Persistence\ObjectManager
        factory_service: elcodi.provider.manager
        factory_method: getManagerByEntityNamespace
        arguments:
            entity_namespace: %elcodi.entity.metric_entry.class%
