services:

    #
    # Services
    #
    elcodi.metric_manager:
        class: %elcodi.metric_manager.class%
        arguments:
            - @elcodi.metrics_bucket
            - @elcodi.factory.metric_entry
            - @elcodi.object_manager.entry

    #
    # Routes
    #
    elcodi.core.metric.routes.input.loader:
        class: %elcodi.core.metric.routes.input.loader.class%
        arguments:
            - %elcodi.core.metric.input_controller_route_name%
            - %elcodi.core.metric.input_controller_route%
        tags:
            - { name: routing.loader }
