services:

    #
    # Services
    #
    elcodi.metric_manager:
        class: Elcodi\Component\Metric\Core\Services\MetricManager
        arguments:
            - @elcodi.metrics_bucket
            - @elcodi.factory.metric_entry
            - @elcodi.object_manager.entry
