services:

    #
    # Twig extensions
    #
    elcodi.api_metric_twig_extension:
        class: %elcodi.api_metric_twig_extension.class%
        arguments:
            - @elcodi.metrics_bucket
        tags:
            - { name: twig.extension }
